---
name: rxnDB
channels:
  - conda-forge
dependencies:
  - python=3.13
  - shiny
  - shinywidgets
  - anywidget
  - pandas
  - plotly
  - kaleido
  - Pillow
  - faicons
  - pip
  - pip:
      - "rxnDB[dev,docs]"
